# docker-compose.yml
services:
  python-app:
    image: ${CONTAINER_REGISTRY_URL:-localhost}/fastapi:${APP_IMAGE_TAG:-latest}
    container_name: fastapi
    build:
      context: .
      target: python-dev
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
