receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp/openobserve:
    endpoint: ${env:OPENOBSERVE_ENDPOINT}
    headers:
      Authorization: Basic ${env:OPENOBSERVE_AUTH_KEY} 
      stream-name: default

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/openobserve]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/openobserve]
